apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicontainer-deployment
  labels:
    deploy: multicontainer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      test: multicon
  template:
    metadata:
      labels:
        test: multicon
    spec:
      containers:
      - name: debian-container
        image: debian        
        command: ["/bin/bash", "-c"]
        args: 
         - while true; do            
            sleep 1;
           done
      - name: nginx
        image: nginx:latest      
  
