apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicontainer-deployment  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-multicon
  template:
    metadata:
      labels:
        app: test-multicon
    spec:
      containers:
      - name: debian-container
        image: debian        
        command: ["/bin/bash", "-c"]
        args: 
         - while true; do            
            sleep 1;
           done
    
      - name: nginx
        image: nginx:latest      
  
