apiVersion: v1
kind: Service
metadata:
  name: nginx-service-1  
spec:
  type: NodePort

  #maapting port
  ports:
  - port: 80

  #send traffic to pods that matching this label selector  
  selector:
    app: nginx
